# Generated by Django 5.2.2 on 2025-09-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Massage level (1-4) for Her Touch services', null=True),
        ),
    ]
