# Generated by Django 5.2.2 on 2025-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='page',
            field=models.CharField(blank=True, help_text="Source page for this service (e.g. 'her_touch', 'her_strength')", max_length=50, null=True),
        ),
    ]
