# Generated by Django 5.2.2 on 2025-08-13 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP Elite')], max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='KSH', max_length=3)),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('her_secrets_access', models.BooleanField(default=False)),
                ('premium_events_access', models.BooleanField(default=False)),
                ('vip_events_access', models.BooleanField(default=False)),
                ('priority_booking', models.BooleanField(default=False)),
                ('premium_gallery_access', models.BooleanField(default=False)),
                ('vip_gallery_access', models.BooleanField(default=False)),
                ('custom_experiences', models.BooleanField(default=False)),
                ('concierge_service', models.BooleanField(default=False)),
                ('private_events', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('features_list', models.JSONField(default=list, help_text='List of features as JSON array')),
                ('restrictions_list', models.JSONField(default=list, help_text='List of restrictions as JSON array')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.CharField(choices=[('basic', 'Basic Member'), ('premium', 'Premium Member'), ('vip', 'VIP Elite Member')], default='basic', help_text="User's current membership level", max_length=10),
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.membershipplan')),
            ],
            options={
                'verbose_name': 'Membership History',
                'verbose_name_plural': 'Membership Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
